akshitagupta15june/PetMe

- index.html
- index.js
- style.css
1. Added a SOS button
2.  The button when clicked redirects to sos report page.
3.  Button also has hover feature >> changes color  of button and font size and  increases the font weight.
> Added the SOS button

- index.html
Fix #9 
Improved the contact-us form.
New form:
> Imporoved contact-us form

- index.html
Resolved issue #59 
Added a blog section in the navbar, which when clicked, opens up the blog.html file; the further processing of the blog.html file has not been done yet, it is just kept blank.
Contributed it under Hacktoberfest'22.
Screenshots :
Do let me know if any other change is required :)
> Added blogs section in navbar

- Contributors.md
- index.html
- introSection.css
- mobileView.css
- Added a new stylesheet named mobileView.css.
- Made intro Background Responsive.
- Revamped the Pet Cards for mobile view (Breakpoint: 768px).
- Navigation
- Please accept it for Hacktoberfest2022.
- Thanks for letting me work on your repo.
> Fix Mobile view #71

- README.md
Resolved issue #57 
Added PetMe Youtube video link in readme section , tried to embed the video but apparently it was not possible .
Contributed it under Hacktoberfest'22.
> Added the Video link to readme section.

- .vscode/settings.json
- reportstary.css
- reportstary.html
This pull request solve issue #21 
I have made a navbar with home,contact and donate element and attach the links with them
> navbar improvement in SOS section

- README.md
Issues
https://github.com/akshitagupta15june/PetMe/issues/45
> Add and center Logo to README.md 

- index.html
- light-dark-theme.js
this affects the following sections: about us, pet details
> fix text on dark mode so its easier to read

- index light.html
- index.html
- output.css
Added the mission "Saving Lives Saving Animals" in the header
> Added mission in the header

- introSection.css
resolved issue #92 
Screenshots :
> Designed the scrollbar

- README.md
Hi 👋 to make it more attractive, I added a preview of the video in the readme.
> Put video on readme

- index.html
- style.css
Add new contact form UI by using tailwind classes.
> New contact form UI

- adopt.html
closes #119
Changed the color of home and added other items along with their link in the navbar of adopt.html
Screenshot
> Made changes to adopt.html navbar

- index.html
- style.css
Thanks for letting me help with this!
> Added GitHub logo, fixed margin and padding around affected areas.

- index.html
- style.css
The color of the two icons are changed from black to white. You can see it in the screenshot.
> changed the color of icons

- index.html
- style.css
Improved Footer UI Using CSS3 and HTML5
___________
Used Flex-Box And TailWind-CSS For Implementation.
I have sent My Pull Request Regarding Issue #132 , Please Merge my Pull Request for The Footer and Ma'am Kindly Please add hacktoberfest-accepted or hacktoberfest tag to my Pull Request while Merging it with the Main branch.
> ADD IMPROVED FOOTER FEATURE

- README.md
Fixes #161 
I have added the section of contribute to the readme.md file
I am open to suggestions and changes.
@akshitagupta15june  Please merge my PR and add the 'hacktoberfest-accepted' label to the PR.
> Added the section of contribute to the readme

- adopt.html
- donate.html
- index.html
- light-dark-theme.js
- navbar.css
- reportstary.html
All navbar buttons now react to hover and change color according to their theme in index.html
Also, theme toggles now feels more interactive as the cursor changes to a pointer instead of being static
Logo also grows on hover and cursor chagnes to pointer instead of text cursor.
> Fixed navbar hover colors and interactivity of logo and theme toggler

- Contributors.md
Added my name to `Contributors.md`
> Added my name to Contributors

- index.html
User is able to submit the form without entering any info. 
Fixes: https://github.com/akshitagupta15june/PetMe/issues/164
- Added html checks to intimate user to enter required information
- Prevented the upfront error shown by Formspree by only submitting form after gathering mandatory info. from the users. 
- Email and Message considered as required data 
(Name not included as users should be allowed to hide their names for anonimity purposes)
> feat(contact-us): added contact form validations

- style.css
Issue fixed is: #160 
(Please mark it as hacktoberfest accepted)
> SOS button UI fixed

- index.html
> Visibility enhancement of Contact Us form

- index.html
- style.css
**BEFORE**
On large screen
**Medium screen**
**small screen**
**AFTER**
On Large screen
On medium screen 
On small screen
> Responsive navbar

- donate.html
#212 
please mark it hacktoberfest accepted. Thanks
> fix: input type of Contact Number

- donate.html
- reportstary.html
Fixed header to be common around all routing. All href were also modified as per pages
> Fixing header around all routing

- reportstary.css
- reportstary.html
> sos-form-responsive

- donate.html
- index.html
- reportstary.html
The hrefs in the nav bar have been fixed on all static pages so they link back to home page when clicked
> Fix link to home page on navbar

- index.html
- introSection.css
- navbar.css
- navbar.js
> Fixed navbar on scroll

- README.md
Added the website preview that is clickable aswell as the social media link.
> Did the updates to the README

- README.md
Fixes https://github.com/akshitagupta15june/PetMe/issues/136
> docs: reduce the size of the video image

- introSection.css
- navbar.css
- navbar.js
added functionality to auto collapse/retreat navbar/header on scroll
> auto collapse/ retreat navbar on window scroll

- reportstary.html
The SOS form to report any critical animal doesn't currently have the address as a required field but should have. Also, it doesn't ask for a contact number which seems essential.
I added these things and also gave some appropriate margins.
> Fixed some issues in the sos form

- donate.html
- reportstary.html
#239 
On scrolling up and down on donate and report stray page, there were errors produced in console, since document.getElementById("header") was null, by adding appropriate id to header tag, this error gets fixed.
> fix console error on scroll,by adding missing id

- Contributors.md
- index.html
fix issue #248 
added color-white class to the text around the contact us page to make the text more clear and visible to the user.
> change font-color of text to be more visible to the users(issue #248 fix)

- Contributors.md
- adopt.html
Fix issue #227
Changed the input type from text to phone to accept only numbers and discard any text.
> fix adopt page input issue #227

- index.html
- introSection.css
now text is aligned to center of the page
> updated introSection.css to fix issue#237

- index.html
- introSection.css
now to font colour of CONTACT US is visible
> Update index.html to fix issue#248

- .gitignore
#259 issue.
This pull request includes .DS_Store to .gitignore file
> chore: prevent osx .DS_Store miscelaneous files

- Contributors.md
Mailed the blog from tannisthabiswasofficial@gmail.com also commented the link
> added my name to contributors.md for sending a blog

- blog.html
- blogs/anuran.html
- blogs/dan.html
- blogs/disha.html
- blogs/elizabeth.html
- blogs/eslem.html
- blogs/omkar.html
- blogs/wesley.html
- index.html
There were some bugs on the blog pages. I fixed them all
Changes:
1. Fix blog.html navbar
2. fix footer logo of all individual blog pages
3. Fix Spelling of "inbox"
4. Fix responsiveness of individual blog pages
> Bug Fix on blog pages

- Contributors.md
- index.html
Addresses issue raised in #278. Contact Us section text can now be seen in light mode.
> Fix light mode for Contact Us section

- index.html
- Revise the language to be more impactful and emotive
- Improve the readability and flow of the statement
> Enhance Mission Statement

- index.html
email given for news letter will be visible which was previously invisible and now will be shown in black color
> solve issue #320

- README.md
>  typo fixed

- adopt.html
- blog.html
- index light.html
- index.html
- reportstary.html
> Added favicon in all pages

- volunteer.html
I updated the box shadow in the Donate form to match all the other forms on the website. 
The shadows were with two different colors #d8740f and #e6b94a. I fixed the styling of the box. 
The box was styled as  box-shadow (line27):15px 15px 20px #d8740f, -15px -15px 20px #e6b94a.
> Update  Donate form in volunteer.html file 

- blog.html
- blogs/abhinav.html
- blogs/alexis.html
- blogs/anuran.html
- blogs/dan.html
- blogs/disha.html
- blogs/elise.html
- blogs/elizabeth.html
- blogs/eslem.html
- blogs/manish.html
- blogs/nalowa.html
- blogs/omkar.html
- blogs/pagsum.html
- blogs/shelby.html
- blogs/tannistha.html
- blogs/wesley.html
- index.html
<strong> added text-black class </strong>
> fixed color issue in newsletter input

- donate.html
- reportstary.html
Fixes - #410
** Solution:- **
fixed css in navbar of donate.html which in the medium size screen.
**Result**
> fixed[#410]- CSS fix of navbar in donate.html

- .vscode/settings.json
- news.html
- output.css
I have worked on the issue #540 and #535 
I have included the  flexbox feature, included some kind of animation effects through css3 and also center-aligned the page items
for your  reference I am also attaching the image and video : 
https://github.com/akshitagupta15june/PetMe/assets/117562053/c509b4ba-5020-42b6-b1d2-d9b1ac4119dd
> Included some features in Pet News Page

- donate.html
Made a single css selection to add apostrophes to all required fields, the benefit from doing it like this is that if a required field would ever be added, it would have the needed apostrophe too. This solves issue #342
> Add Apostrophes to Required Fields in Donate Section

- index.html
Wrapped the img tag in a link tag and referenced it to the top of the page...
> Bugfix:362_Make PetMe Icon at the footer scroll the page to the top

- README.md
There were a few grammatical error that I removed.
> Removed the basic grammatical errors in the Readme file. [GSSoC'23]

- index.html
fixes [#582]
achieved expected behavior.
> fixed{#582} fixes-css in index.html

- server/Models/userModel.js
- server/app.js
- server/package-lock.json
- server/package.json
- server/routes/userRoutes.js
- server/utils/userAuth.js
@akshitagupta15june I have worked on the user login and register API.
It is working and functional, please find attached images of the endpoints in action on postman
I look forward to working on another issue, probably an Admin feature
> User Login and Register

- index.html
- navbar.css
- style.css
1.Now the website **has a fixed Navbar** on the **top throughout.** 
2. The "Adopt Me" button seemed too small and was just the size of the cursor so increased the size of the box for easy visibility and interface and added hover to it. making it look more attractive and clickable to the user.
> Assigned Task Complete ( Fixed Navbar & Hover Added )

- index.html
- introSection.css
Issue number: #415 
Description: 
This PR enhances the "Adopt Me" section by adding a gradient overlay to the background, adjusting its opacity, updating the heading text style. These changes improve somehow the section's visual appeal and user experience.
Screenshot: 
Old:
Updated:
> Improve hero section heading and paragraph

- news.html
Addresses issue #780 
Close #780
I have added a footer similar to other pages, in the Pet news section
> Added footer in Pet news

- src/components/ContactForms/ContactForms.test.jsx
- src/components/ContactForms/index.jsx
- src/components/Contributors/index.jsx
- src/components/VolunteerForms/index.jsx
- src/main.jsx
- src/pages/App.jsx
- src/pages/ContactUs.jsx
Issue addressed: https://github.com/akshitagupta15june/PetMe/issues/808
This pull request comprises the implementation of the following items:
- Page "ContactUs.jsx"
- Route to the respective page on "main.jsx"
- Updated component "ContactForms/index.jsx"
- Basic testing of the respective component (jsx elements)
- Minor adjustment on "src/components/VolunteerForms/index.jsx" (eslint issue)
> [Issue 808] Contact Us Page implementation

- news.html
> fixes [#624]

- index.html
#617 I added a button in navbar so user can directly go to meet pets section and see pets that are available for adoption.
Suggest me any required changes further if needed. #617
> added meet pets in navbar

- adopt.html
- reportstary.css
Resolves #508 
Updated: 
1. Added designs to the form 
2. Added a div and image to fill the page
3. Used icons/svgs to make it more user friendly
4. Used colors and theme according to the website
before changes:
after changes:
> UI: Improved adopt page

- index.js
- introSection.css
Closes #716
Added dynamic background image slideshow to main section. Please review.
- static background 
- dynamic background 
https://github.com/akshitagupta15june/PetMe/assets/83013408/be858977-63eb-452c-bc7c-e7cc9eb33e9a
Any kind of feedback would be appreciated.
@akshitagupta15june @Susmita-Dey @muditchoudhary @akshaaatt
> Implemented dynamic background image slideshow in main section

- style.css
- volunteer.html
the overlaping issue between the navbar and text form in become a volunteer section is removed
> Issue of overlaping between the navbar and text form in become a volunteer section is resolved

- adopt.html
- blog.html
- donate.html
- index.html
- news.html
- style.css
- volunteer.html
Refer pr #675  for the implemented changes.
Opened second pr due to branch conflicts in the previous pr.
> Made navbar more prominent and buttons

- src/components/Footer/index.jsx
Resolved the UI issue in the footer Subscribe Email field.
> Email input UI fix in the footer menu 

- index.html
- style.css
Clears #365 
Added a small fade-in effect to the form, when someone scrolls down and reaches for the contact form, the form will fade in from the right slowly giving an alluring effect.
https://github.com/akshitagupta15june/PetMe/assets/95973644/5163d1f0-22a5-44a1-9013-4905f7b41e95
> Added fade-in for contact form

- donate.html
Hello Team,
I wanted to let you know about a problem with the submit button on the donate page. When users hover over it, the button becomes too long and doesn't look right. I've made some changes to fix this issue. Please take a look at the attached video that shows the problem before and after the changes. I believe these changes will make the donate page look more professional and user-friendly.
**Before:**
https://github.com/akshitagupta15june/PetMe/assets/77961384/357f0b83-6986-4676-9048-3a4d191e4f39
**After**
https://github.com/akshitagupta15june/PetMe/assets/77961384/086bac0f-835c-4387-b5bc-4b3e5d63f2bf
> Changed The Submit Button on The Donate Page.

- Contributors.md
- donate.html
Made the changes asked in the issue and also added a little bit of padding to the navbar, since the navbar was almost touching the text "Donate Animals".
Before : 
After :
> Fixed the issue #876

- blog.json
- To Remove duplicate kafka blog.
> remove duplicate kafka blog

- src/components/Header/index.jsx
- Add a modal to the header for the Contact Us form.
- I have started working on the form for the mobile version, but it hasn't been implemented yet.
> feat: add contact us functionality on header

- package.json
- src/components/News/index.jsx
Added the date format in the petnews screen
> Added the date format in the Petnews screen

- navbar.css
> Changing NavBar height

- blog.html
I have removed the meet pets and about us from blog section. Kindly merge it.
> Changes made in blog section

- reportstary.html
removed about us as described in the ticket
> removed about us from reportstary.html

- volunteer.html
Hello Project Admin,
- [] I have created a helpful and easy to understand `README.md`
> Modified  Volunteer Page Bug Fixed

- reportstary.css
- reportstary.html
- reportstary.js
ref.- Issue no. #760
added a help button on the SOS page that brings a popup like this- 
This is a feature in help section where people can search pet clinics near a city , like they search "jaipur" then it'll take them to the clinics detail page on "justdial".
trying this feature under GSSOC'23.
> Added help section in SOS Page

- blog.html
- index.html
- news.html
- style.css
close issue -> #773 
data is taken form your license a there mention 2022 so write as it is.
> copy right footer is added in all pages

- blog.js
Implement smooth scrolling feature for blog content issue -- #909 
Enhance the user experience by adding smooth scrolling functionality to the blog page. When users click on a "Read" link, the page now smoothly scrolls to the corresponding blog content, providing a seamless browsing experience. This is achieved using the scrollIntoView() method with the behavior option set to 'smooth'.
> Add smooth scroll functionality to blog page issue-- #909

- volunteer.html
Before:
After:
Clears issue #676 
The main issue to fix the hover was done by someone else but the basic hover effects were removed, added the basic hover effects to the button and some border radius
> Added hover effects to the button

- style.css
The text in Adopt Me has been successfully fixed and is now clearly visible. 
Additionally, I have also rectified the text on the card, ensuring its readability and clarity.
Closes #923 
in light mode
in dark mode
> adopt me text is fixed 

- index.html
Alignment of contact us section is fixed. Kindly preview and merge. 
https://github.com/akshitagupta15june/PetMe/assets/102872838/c5ebf3dc-5620-4eae-92ac-c7bc3e98fa8d
> Alignment of Contact Us Section

- reportstary.html
> removed contact us section in SOS report page

- index.html
- introSection.css
Fixed #930 
I've updated the UI of the Homepage and have done the following changes:
<hr>
- I've corrected the color of the div below the about us section in homepage, and have placed it instead inside the pet-cards section as a separate element. 
<hr>
- I've enhanced the size of several headings in homepage and added the antialiasing and smootherning effects. Also, some headings, such as the "About Us" had **hover:underline** property as default which wasn't functioning. I've fixed that and replaced the underline with overline, which gives much better view. 
<hr>
- I've also correct the colors of buttons and other elements in the footer section of the index page.
> Enhancing the UI and color combination of homepage

- index.html
> fix: overlapping buttons

- news.html
Issue #874 
Close #874 
Removed the meet pets and about us from navbar of pet news section
> Removed meet pets and about us

- index.html
> fix: 'meet up' button in navbar

- index.html
I just fixed the About Us scroll problem and also re-designed a bit. Please let me know if something more is needed to be done. Fixed the issue #966 .
> Made the changes, Fixed About Us scroll

- index.html
This pull request introduces several enhancements to the footer:
1) Changed the subscribe button color from yellow to red to improve visual aesthetics. On small screens, the button already displayed as red, and on larger screens, its color has been set to "br-red-500", while on hover, it now uses "bg-red-600".
2) Added padding to the top and bottom of the footer to enhance its appearance.
3) Addressed an issue on small screens where the "Subscribe to our Newsletter" section in the footer had a gray background, which negatively impacted the overall design. This has been corrected, and the background now remains black on all screen sizes, ensuring a consistent and more appealing look.
> Enhanced footer: padding, button color for large screens, standard look for small screens.

- image.svg
- index.html
- style.css
Solved the issue #1006 . 
Video : 
https://github.com/akshitagupta15june/PetMe/assets/127319225/f56727d7-8412-47ef-9bf5-3743e92cc166
> Added Hover effect to the Scroll to Top Button and also changed the Scroll to top icon

- index.html
This pull request includes the following enhancements:
1- Improved text readability by updating the text color from "text-gray-500" to "text-gray-200," resulting in a more visually appealing appearance.
2- Implemented hover effects for the "About Us" heading (h2) to enhance its visual presentation.
> Polished About section: text color and hover effects

- Contributors.md
Adding me to the contributors list
> Updating Contributors.md

- news.html
Closes: #1024 
Improved:
- Functionality & appearance of header
- Matched footer with design of website
- Matched backtotop button with other pages
> fix: Enhanced news page

- Contributors.md
Adding me to the contributors list
> docs: Update Contributors.md

- index.html
- style.css
Fixes issue #1044 .
Video : 
https://github.com/akshitagupta15june/PetMe/assets/127319225/b10e8874-da1f-4a27-ad6b-509d605164c9
> Added Reveal scroll to Meet Pets section

- blog.html
- index.html
- style.css
Added hover effect on the social media icons.
> add hover effect on social-media icons

- index.html
Solved  issue#1056 : https://github.com/akshitagupta15june/PetMe/issues/1056#issue-1865411631
> Removed SOS button

- blog.html
Resolved issue #1074 .
Video : 
https://github.com/akshitagupta15june/PetMe/assets/127319225/23847616-f7ab-40e0-892f-f306613f98f2
> Resolved the "Scroll To Top" button issue

- index.html
- style.css
#To Fix The ISSUE
- Updated some code in Style.css
- Added "color: #181717;" in Button Text
```code
.hover-button {
color: #181717;
}
```
#After
> Fixed Issue #1061

- blog.html
- index.html
- news.html
**Before:**
**After:**
Added this code in all three pages
> fixes copyright section

- donate.html
Made the changes, turned autocomplete off
Screenshot: 
Closes issue: #1085
> Updated form; addressed issue: #1085

- reportstary.css
Here's the PR that fixes the issue for the SOS form layout.
> Fixes issue #1092

- volunteer.html
So as mentioned in the issue #1099 , I updated the submit button which was not matching to the whole website ,
Now the color of the submit button matches to the color of navbar and whole website.
Have a look at it and merge my pull request @akshitagupta15june @Susmita-Dey
> Submit Button improved

- adopt.html
https://github.com/akshitagupta15june/PetMe/assets/91741581/65154852-3d2c-47ed-929e-02b8f02c880e
Closes #1081
> Fixes adopt form

- index.html
> About us content Font-color changed to black in NIGHT mode

- adopt.html
Changed the icons position and now they are placed correctly
Before:
After:
> Changed icons position in "Adopt me" page

- blog.html
- blog.js
As mentioned in the issue #1135 , improved the color of the read button in the blog article , Now the color of the button matches to the whole web page and it's navbar also it takes us to the different html files present for all different blogs.
Please have a look and merge my pull request @Susmita-Dey @akshitagupta15june
> Blog article improvemnet

- reportstary.html
Fixes #1149
**Please add “hacktoberfest-accepted” label**
**Please add “hacksquad” label**
**Before -** 
**After -**
>  Fixed h1 of SOS

- index.html
In response to issue:
🐛🐛Bug Report! Issue with alignment of navbar in mobile view. #1169
https://github.com/akshitagupta15june/PetMe/issues/1169
> fixed_nav_alignment

- reportstary.js
Fixed #1157 Updated the section, so that an alert pops up when user doesn't enter any city name.
> Fixed #1157 Empty input handle in the Help Popup in SOS screen

- index.html
Fixed issue #1160 
Clicking on Adopt,
It shows this section 👇
> Fixed: Bug in the About Us section regarding Adopt link

- blog.html
- style.css
@akshitagupta15june  I have changed the design of the select language button making it look more appealing,
It looks something like this rn -
kindly merge it :)
fixes #953 
fixes #1145
> fixed design of translate button of navbar

- README.md
I have updated README.md with the current website images as it had the outdated images.
Kindly review this PR under hacktoberfest 2023. Thanks You!
> Updated README.md With New Website Images

- adopt.html
After adding the correct path, now the Nav links are working correctly
https://github.com/akshitagupta15june/PetMe/assets/113518358/161f40a3-7e6f-4220-ae3f-affa1ebfae94
> Nav links has been edited

- blogs/abhinav.html
- blogs/anuran.html
- blogs/dan.html
- blogs/disha.html
- blogs/elise.html
- blogs/elizabeth.html
- blogs/eslem.html
- blogs/manish.html
- blogs/nalowa.html
- blogs/omkar.html
- blogs/shelby.html
- blogs/tannistha.html
- blogs/wesley.html
I have corrected the date spelling (October) in user blogs.
> Corrected the date mentioned in user's blogs.

- volunteer.html
ADD FOOTER SECTION IN VOLUNTEER PAGE
Add the footer section in volunteer page improve the UI of the page.
Screenshort::
Without Footer Tag:
With Footer Tag:
Solve Issue #1121
> Add Footer Section in Volunteer Page

- reportstary.html
I hope you accept my PR, thanks. Screenshots detailing the changes are as below.
Before:
After changes:
> Fixes issue #1171

- index.html
- index.js
closes #1134 
https://github.com/akshitagupta15june/PetMe/assets/71914071/16eef86c-85aa-4af3-ac61-8990e35d3d52
> Fix: Functionality of subscribe button

- index.html
This PR fixes issue #1176. Below are the screenshots detailing the changes:
Before:
After changes:
> Fixes issue #1176

- blogs/disha.html
I have added some more details to the blog. Please merge my pull request
> Update disha.html- Added some more info

- index.html
Before: 
After appropriate changes: 
fixes #1184 
Please review it @akshitagupta15june :)
> Fixed : Shadow issue in Dog-Sheru Adopt me card.

- adopt.html
As mentioned in the issue #1196 , solved the issue 
the bug was in the navbar where volunteers registration markdown had a ugly styling.
Now it has been updated , Have a look 
Please merge the pull request @akshitagupta15june  @Susmita-Dey
> Adopt File

- donate1.html
Closes #1239 
Screenshots detailing the changes:
Before:
After changes:
> Fixes issue #1239

- index.html
Closes issue #1182 
Video : 
https://github.com/akshitagupta15june/PetMe/assets/127319225/57bacaec-cd19-48ed-a524-f8243f7188b8
> Centered the elements of navbar

- index.html
before the button name was wrong 
after fixing the button name 
fixed this issue : #1142
> submit button fixed

- index.html
- style.css
issue number #1212 
Description:
Our website's social media icons are essential for connecting with our audience and sharing content. To enhance user engagement and elevate the overall aesthetics, I recommend improving the responsiveness and vibrancy of these icons.
Solution:
To achieve this, I've made the following enhancements:
Aligned the icons' colors with their respective logos for better visual recognition.
Implemented a smooth transition of 0.3 seconds with a hover effect, enhancing responsiveness and providing users with intuitive feedback when interacting with the icons.
These changes result in a more vibrant and user-friendly experience, encouraging increased engagement with our social media channels.
> icons-updated

- volunteer.html
Added the missing Nav links to the Support us page.
> Added About us,Pet news and Contact us links to the nav

- reportstary.css
in response to issue https://github.com/akshitagupta15june/PetMe/issues/1202
> Fixed the visibility of help button in mobile view.

- Contributors.md
ref #34
Added myself to the contributors list.
> Add Contributor

- index.html
This pr fixes #1195 
I have added the required javascript to close the menu when a nav link is clicked in small screen.
> [Fixes #1195] Added javascript to close menu

- news.html
FOR ISSUE : Meet Pets in news page not working #1217 
Solved the link problem.
> fixed meet pets issue

- adopt.html
- blog.html
- donate.html
- donate1.html
- index.html
- light-dark-theme.js
- navbar.css
- news.html
- reportstary.html
- volunteer.html
This PR adds the **Hovering Effect** on the **Change Theme Icons**.
Fixes #1165 
Hi @akshitagupta15june, If you consider this PR to get merged, please added the label `hacktoberfest-accepted` to it. It is necessary for the PR to have this label as per the guidelines of Hacktoberfest.
> 🐛 Bug Report: Added 'Hovering Effect' on 'Change Theme Icons'

- .github/Pull_Request_Template.md
Closes: #1220 
Added a similar Pull Request Template like [Moksh](https://github.com/akshitagupta15june/Moksh)
> Chore: Create Pull_Request_Template.md

- reportstary.css
- reportstary.html
Closes: #1235 
Added footer In "SOS" page.Ans also moved the "HELP" button a little towards right as it was coming on the Footer logo's.
Before:
After:
> Added footer in SOS page

- index.html
Closes: #1233 
The nav address of Donate in Home page has been changed to "donate.html".
> Nav link has been changed from donate1.html to donate.html

- index.html
Closes: #1278 
The visibility of contact us form text was very low in dark mode. That has been fixed
> fix: Contact us form text visibility in light mode improved

- index.html
This PR updates the updates the similar **Hovering Effect** on **Social Icons** of `Home` section.
Fixes #1263  
Hi @akshitagupta15june, If you consider this PR to get merged, please add the label `hacktoberfest-accepted` to it. It is necessary for the PR to have this label as per the guidelines of Hacktoberfest.
> 🐛 Bug Report: Updated 'Hovering Effect' on 'Social Icons' of 'Home' section

- adopt.html
This is the pull request for the issue:-
[BUG]Adoptme page Icon fix #1259 
Fixed the logo issue.
> solved layout of logo

- donate1.html
Closes #1256 
Screenshots detailing the changes:
Before:
After changes:
> Fixes issue #1256

- style.css
**Fixes issue** #1249 
**Enhanced Social Media Icons Styling for Improved Consistency and Visibility**
I've refined the styling of our social media icons, ensuring a **consistent** and **visually appealing** look. I've also made sure that the icons are clearly **visible** and that the **hover effect works seamlessly.**
**Screenshots:**
https://github.com/akshitagupta15june/PetMe/assets/110025628/bdef9b0f-532c-48b3-918a-25203213303a
**Note to Reviewer**
I kindly request that the following labels be added to this pull request: `hacktoberfest` and `hacktoberfest-accepted` . Thanks!
> Refactor: Refined Social Media Icons

- blogs/Phoenix.html
Type of change
Enhancement.
Resolves https://github.com/akshitagupta15june/PetMe/issues/1120
Tasks Done
A new blog has been written up and added to the other blogs.
The blog has been converted to conform to the html format.
A new photo (b22-poster.png) has been added to the img folder
Code has been updated, review and checked to become accessible and visible on the PetMe page
Before:
After:
> Added new blog

- adopt.html
- style.css
Added Footer in adopt me page.
Closes: #1285 
Successfully added the footer and kept the basic layout same
> Added footer in adopt.html

- index.html
Closes: #1242 
This pull request addresses the issue of **font color inconsistencies** in the website's **light mode**. It ensures that font colors provide **good contrast with the background, enhancing readability** and improving the **user experience.**
- Adjusted font colors in various sections of the website to ensure consistency and readability in light mode.
https://github.com/akshitagupta15june/PetMe/assets/110025628/e9f96151-ef51-4200-9c6a-7e419e22ea57
Kindly mark it as `hacktoberfest` and `hacktoberfest-accepted`.
> fix font colors for light mode

- donate1.html
- index.html
- server/package-lock.json
- server/package.json
- style.css
- volunteer.html
Closes: #1227 
Changing the ui of the adopt me button
After
Before
> Fix adopt button ui 

- blog.html
Closes: #1309 
Added "Meet pets" and "About us" links to the nav of blogs page
Before:
After:
> Added the missing links to nav

- index.html
- index.js
- site.webmanifest.json
Closes: #1261 
In this pull request, I addressed several issues within the project to improve its overall stability and user experience.
**1. Resolved console errors:** I identified and fixed various console errors, enhancing the project's reliability and reducing potential issues.
**2. Addressed TypeError:** I fixed a TypeError that was affecting the project's functionality, ensuring smoother operation.
**3. Manifest Improvement:** I made improvements to the manifest file to enhance the project's performance and user experience.
**4. Dark Mode Enhancement:** The dark mode feature is now fully functional, providing users with an improved visual experience in low-light conditions.
_No Console Errors and DarkMode functionality working_ …
> Fix Console Errors + Dark Mode functionality

- README.md
> removing maintainer

- index.html
Solve the issue #1280 
The submit button was not matching now it's perfect with the page styling 
Have a look @akshitagupta15june
> Submit button of form 

- Contributors.md
- blog.html
- index.html
- style.css
Closes: #1339 
The button has some design issues which I will fix with this PR.
> Fixed Go to Top Button Alignment

- news.html
Closes: #1283 
Nav link of contact us has been resolved.
> Contact us nav link has been resolved

- blog.html
Closes: #1303 
UI of Contact Us button on blog page made uniform wrt to other pages.
Before:
After:
> fix: UI of Contact of button made uniform accross all pages

- blog.js
Closes:  #1372 
Before 
After
Fixed Button Alignment and added target to open Links in new Tab for better user experience.
> Fixed Read Button in /blog and gave target to link

- donate.html
- volunteer.html
Closes: #1099
change the submit button hover effect according to the webpage theme 
sorry, can not take screenshot of the hover effect
- [ x] My code adheres to the established style guidelines of the project.
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
> Submit button in Volunteer Page

- donate.html
Closes: #1365
changed the submit button in the donate.html its color is not matched to the webpage theme after update the button it matched to the the of the webpage
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
> changed the submit button color

- README.md
> Updated and corrected readme

- index.html
This PR fixes the contact form text, button and else. in both light and dark mode all text and button visible now.
Closes #1364 
https://github.com/akshitagupta15june/PetMe/assets/146264364/525b6dd1-fd1c-4022-99c4-736df0628126
> <Fixes Contact Form>

- reportstary.html
Closes: #1343 
Footer and scroll to top has been added
> fix: added missing footer and scroll-to-top in sos page

- blog.js
Reverts akshitagupta15june/PetMe#1373
> Revert "Fixed Read Button in /blog and gave target to link"

- news.html
Closes: #1266
**Description-**
Fixed padding and margin of News Page Heading
**Before-**
**After-**
> Fixed padding and margin of News Page Heading

- Contributors.md
Added github profile in Contributors.md
> Added github profile in Contributors.md

- volunteer.html
Closes: #1408 
Cursor changes to pointer.
> fixed cursor attribute

- index.html
Enhance data entry accuracy by introducing thorough validation checks in the 'Name' field of the contact form. This commit aims to improve user input accuracy, ensuring reliable and error-free data submission.
Closes: #1419 
This project focuses on enhancing user data accuracy in a contact form by implementing robust validation for the 'Name' field. The HTML input is dynamically validated using JavaScript, ensuring that users provide only valid characters such as letters, hyphens, and spaces. Real-time feedback is provided, with an error message displayed for invalid inputs and a clean visual cue with border color changes. By incorporating this validation mechanism, the contact form becomes more user-friendly, guiding users to submit accurate and reliable information. 
- [X ] My code …
> Implement robust validation for 'Name' field in contact form

- Contributors.md
- blog.html
- blog.js
- index.html
Closes: #1430 
- Modified Contributors.md
- Updated blog.html and blog.js to improve the blog layout
- Changed text color to white for better readability
- Made the 'Read' button appear on a separate line
- Minor changes to index.html
Original
Changed
> Update blog layout and enhance readability

- reportstary.css
The background of the footer is fixed.
Closes: #1432 
Added a CSS for the footer subscribe form
- [x ] My changes have not introduced any new warnings.
> Fixed issue #1432

- volunteer.html
**#1408**
The issue is solved.
> #1408 Solved

- blog.js
- style.css
Closes: #1473 
Added a proper hover styling
> Improve the adopt me button 

- blog.js
> Update the blog file 'read' buttons 

- reportstary.css
Closes: #1449
i changed a line of css code to fix the button issue from moving across the page by using position : absolute instead of position :fixed
> changed button from fixed to absolute

- blogs/Phoenix.html
- blogs/abhinav.html
- blogs/abhishek.html
- blogs/alexis.html
- blogs/anuran.html
- blogs/arvind.html
- blogs/dan.html
- blogs/disha.html
- blogs/elise.html
- blogs/elizabeth.html
- blogs/eslem.html
- blogs/manish.html
- blogs/nalowa.html
- blogs/omkar.html
- blogs/pagsum.html
- blogs/prasanna.html
- blogs/rayarka2.html
- blogs/rayarka26.html
- blogs/rayarka3.html
- blogs/shelby.html
- blogs/shruti.html
- blogs/tannistha.html
- blogs/vidhisha.html
- blogs/wesley.html
Closes: #issue_number
issue number: #1584
Made changes in the blog section so that it become responsive for different screen size.
> added responsiveness in the blog pages

- blog.html
- news.html
Closes: #1673
On a desktop screen navbar is ok but when we try to go  down from extra large screen sizes the **Logo** of this website gets affected as you can see in the image below. It impacts the user experience. So, for improving this i have changed the media query in which instead of going down from large screen we see this mobile navbar i have added instead of below xl screen so that ui section of navbar not gets affected and gets better user experience. 
Before :-
After :-
> Updating the Navbar of News and Blogs page for better User Experience

- blog.js
Closes: #1562 
- [x ] My changes have not introduced any new warnings.
> Fix: Position-of-Read

- introSection.css
Closes: #1604
Border radius should be less for good looking UI
> change in border radium

- reportstary.html
- reportstary.js
Input box for other stray animals added. Please take a look.
Before :
After :
> inputBoxForOtherAdded

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/ISSUE_TEMPLATE/feature_request.md
Closes: #1555
Updated the issue templates , added  new labels with template  and  new file for bug .
> docs: update issue template

- adopt.html
- blog.html
- index.html
- news.html
Closes: #1684 
Adding Valiadtion in the Contact and Adoption form for better user experience.
Before :-
After :-
> Adding Validations for Contact and Adoption form

- blog.html
- news.html
Closes: #1681
The Pet News Navigation link is disappearing when we click on it.  That actually happens because the link is not added inside the html file of this. So i have added this link in it.
Before:-
After :-
> Not to disappearing Pet News link on clicking it.

- blog.html
- blogs/blog.css
- light-dark-theme.js
Closes: #1636
i started adding CSS to bring dark mode in the blog.html page. will continue changes.
> begin blog darkmode

- index.html
##What does this PR do?
This PR changes the font weight of texts in the footer sections
#1700 
**Before setting font weight to medium**
**After setting the font weight to medium **
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
> Increased the font weightto medium  in footer section

- reportstary.css
- reportstary.html
- reportstary.js
Closes: #1640
The issue regarding the live location sharing feature for the SoS form has been resolved by using : 
1. Geolocation Fetching: Utilizing the browser's Geolocation API to fetch the user's current latitude and longitude when they click the "Locate Me" button.
2. UI Integration: Displaying the fetched address in the form's location input field, making it easy for users to see and confirm their exact location.
3. The Geolocation API requires user permission to access location data.
4. Accuracy can be affected by device capabilities and environmental factors.
> Added the live location feature in the SOS form for live location sharing of the injured/stray/needy animal.

- blogs/Phoenix.html
- blogs/abhinav.html
- blogs/abhishek.html
- blogs/alexis.html
- blogs/anuran.html
- blogs/arvind.html
- blogs/dan.html
- blogs/disha.html
- blogs/elise.html
- blogs/elizabeth.html
- blogs/eslem.html
- blogs/manish.html
- blogs/nalowa.html
- blogs/omkar.html
- blogs/pagsum.html
- blogs/prasanna.html
- blogs/rayarka2.html
- blogs/rayarka26.html
- blogs/rayarka3.html
- blogs/shelby.html
- blogs/shruti.html
- blogs/tannistha.html
- blogs/vidhisha.html
- blogs/wesley.html
Closes: #1733
#And please add GSSOC level to it
> Content alligned properly inside blog read

- adopt.html
Closes: #1727 
In  adopt form , there are two forms for adoption , 
I solved this bug .
**Before** 
https://github.com/akshitagupta15june/PetMe/assets/132470460/d5919089-7435-41e7-81f9-e535f36a3f50
**After** 
- [ x] My code adheres to the established style guidelines of the project.
- [ x] My changes have not introduced any new warnings.
> Update the  adopt form

- index.html
- introSection.css
- navbar.css
- style.css
Closes: #1732
https://github.com/akshitagupta15june/PetMe/assets/168094736/1f961554-fc7f-4c1e-95fd-14371d7a2063
> new nav bar

- blog.html
Updating blog containers uniform with issue #1705 
Closes: #1705 
just made the containers of blog file uniform
> Updating blog containers and ui changed

- donate.html
- light-dark-theme.js
Closes: #1356
fixed dark more in the donate.html file and added LinkedIn handle below
> fetched and merged

- blog.html
Closes: #1784
the footer section is esaily visible , i changed the text color as white ;
- [ x] My code adheres to the established style guidelines of the project.
- [x ] My changes have not introduced any new warnings.
> fix :-  #1784 subscribe/footer section text is not visible has been updated 

- index light.html
- index.html
Closes: #1784 
This PR addresses the issue where the footer text was not visible in certain themes (#1784). The footer text color has been updated to ensure it adheres to the current theme and UI color palette, improving readability across all themes.
> Bug footer fix branch

- index.html
Closes: #1779 
Support Us section was not navigating to volunteer page in index page.
https://github.com/akshitagupta15june/PetMe/assets/144598258/2c038645-cb9e-4a5a-8d7f-0cee255a1d4d
After fixing the bug the Support Us section started working properly.
https://github.com/akshitagupta15june/PetMe/assets/144598258/4d0e9db6-fd33-4c04-98a6-bb0020d8209b
> Fixed Bug #1779

- blog.html
This PR sets the color of the footer text on blogs page to white on full screen so that the text is visible.
Closes: #1842  
**BEFORE**
This was the footer on larger screen the text was not visible on the dark background
**AFTER**
This was after the color of the text is changed so that it is clearly visible
> Added white color to footer text for visibility

- index.html
Closes: #1825 
The components in nav bar were not looking appropriate and seemed to be messed up a bit. I changed the text size to make it look cleaner and nicer.
> Changes in UI of nav bar in menu

- reportstary.html
Hello PA @akshitagupta15june 
Issue resolved - #1841
> Fixed form in dark theme

- index.html
- light-dark-theme.js
- style_PetCards.css
Enhancing Cards and background of "PET Adoption Cards section" #1724
Closes: #1724 
Enhanced  the Pets cards section for both light mode and dark mode  respectively
This is of hovering upon the card.
> Updated PetCards section in Dark and LightModes Respectively.

- index.html
- navbar.css
- tailwind.config.js
Closes: #1563 
the home page navbar has various hover bugs. I have fixed those by changing some code to make the navbar responsive.
> fixed the hover effect on new pet page #1563
