- README.md
Fixes #36 
Added the shields.io badges to reflect the GitHub repo stats (such as issues, PRs, forks, and stars).
Attaching a screenshot below
Do let me know if anything needs to be changed.
> Github Readme stats

- Contributors.md
Add Elizabeth McCready - GingerKiwi to contributors. Blog post link: https://medium.com/@gingerkiwi-dev/tips-for-new-feral-rescue-kitten-owners-part-1-of-3-bc6d21da2dd9
> Update Contributors.md to include Elizabeth McCready - GingerKiwi 

- blog.html
This is to to fix the about us link on the nav bar of the blog page. Now the about us link redirects to the about us section on the homepage.
Issue #266
> Fix about us link on blog page

- index.js
- style.css
- Add transition styling to the existing Back to Top button
- Improve the button's appearance with the transition effect
- Enhance UX by adding animation when the button appears and disappears
- Use CSS opacity transition to achieve the animation effect
> Add transition styling to the back to top button

- index.html
- style.css
This pull request improves the "back-to-top" feature by moving it to the top of the hero page and making it fixed for increased visibility. This enhancement aims to make it easier for users to quickly navigate back to the top of the page, enhancing their overall experience.  under **GSSOC**
closes: #416 
when I started working on the page, I noticed that the feature  has already been implemented. What i did  was to move it to the top and ensure it remains fixed in order to enhance the user experience and improve its visibility.
> Enhancing visibility and user experience: introducing the scroll-to-feature functionality on hero page

- blog.html
- news.html
The contact form on the "Pet News" and "Blog" pages did not exist, therefore the button did not work, I redirected the action of the button to the main page where the form is located.
> Contact button fixed on blog page & Pet News

- news.html
fixes #1087 
So let me explain the issue here, 
"About US" is a section in index.html page. So it can be accessed only in Index.html file. But it was being called from news.html
So all we need to do is add index.html#About in order to redirect to the actual About Us section.
Hope this helps...
> Updated About US

- news.html
This PR adds the **Hovering Effect** on the Social Icons in the `Pets News` section.
Fixes #1166
Hi @akshitagupta15june, If you consider this PR to get merged, please added the label `hacktoberfest-accepted` to it. It is necessary for the PR to have this label as per the guidelines of Hacktoberfest.
> 🐛 Bug Report: Added 'Hovering Effect' on Social Icons in 'Meet Pets' section

- index.js
- style.css
**Description:**
This PR addresses the issue of the scroll-to-top button always being present, even when the user has just opened the website or when the page is already at the top. The scroll-to-top button **should only be displayed when the user has scrolled down the page.**
**Screenshots:**
_Before (scroll to top button is always present):_
https://github.com/akshitagupta15june/PetMe/assets/110025628/9a630023-2ca2-4caf-93b1-a561049e46ba
_After (scroll to top button appears only when the user scrolls down):_
https://github.com/akshitagupta15june/PetMe/assets/110025628/a585a616-cb81-420b-8d75-ea3636d2439d
**Note to Reviewer:**
I kindly request the reviewer to consider marking this pull request as `"hacktoberfest"` and `"hacktoberfest-accepted"`.
> Fix: Scroll-to-top button display

- reportstary.css
Closes: #1334
Fixed Position of Help Button. Earlier it was not visible in mobile view, now I have fixed it.
Before:
After:
> Fixed Position of Help Button

- index.html
Closes #1324 
The PetMe logo in the header enlarges upon hover currently.
To keep the same continuity in the footer and better visual appeal, this PR does the same by making CSS changes inline using Tailwind CSS classes.
Before:
After changes:
> Fixes issue #1324: Enlarges PetMe logo upon hover in footer

- navbar.css
Closes: #1363
Whenever theme toggle button be clicked, the dark-theme class get toggled but the light-theme class not, it applies font-size:1.5 for the whole body tag, leads to the glitch in font size of the Submit button (as well as the placeholder of the text area right above and maybe somewhere else).
I gather all the common styles and put all of them into '#switch', keep only necessary styles used for switch button, add prefix "#switch" in order to use .dark-theme locally, as well as increase priority of :hover actions, ensure that their color style are not overwritten by .dark-theme class.
> Fixed button size glitch in light and dark theme

- index.html
Closes: #1367 
Usually websites have call-to-action button to increase the conversion of users to do specific task for example: Register, Sign-In, Volunteer, Participate, etc. One of the main idea and motive behind this initiative is to connect people to create a better world for all animals but the site is missing a strong call for people to come together. So to overcome this we can either have a CTA button or a CTA link in the About Us section of Index Page that takes the user to the Volunteer page
CTA Button:
CTA Button when hovered:
> added button to link volunteer page to increase conversion

- introSection.css
Closes #1345 
Now the colour of the subheading stays white upon toggling the theme to light mode. A simple CSS style change has been made to the 'introSection.css' file.
Before:
After changes:
> Fixes issue #1345 : Improved readability for sub-heading

- blog.html
- donate.html
- index.html
- news.html
- reportstary.html
- volunteer.html
Closes: #1300 
It was observed that some pages did not have favicon upon visiting.
namely: `pet news` , `volunteer` or `donate`
> Fixed Favicon not rendering Issue

- navbar.css
Fixes: #1350
**Bug Fixed:-**
In the navbar below the translate searchbar "Powered By" is written whose sense is incomplete without "Powered by Google".
Upon inspecting I found that CSS has been written to hide it, "Google Translate" img is hidden by that but it is not being reflected on "Powered By", it is being overridden by some other properties.
I have fixed that issue.
**Before**
**After**
> Fixed: Overriding CSS Properties of Google Translate Bar

- index.html
text in Contact Us section of main page is now visible in dark and light mode
Closes: #1403
Before:
After:
> #1403 solved

- reportstary.css
##1482
Closes: #1487
the help button overlap with form input from 1200px width to 400px width
- [ x] My changes have not introduced any new warnings.
> making small tiny change to fix overlapping

- index.html
Closes: #1668 
One common issue is that the absolute positioning combined with the fixed width (w-[7.5rem]) might cause the content to overflow the container in smaller screen widths.
To overcome this problem we can introduce -
1. Responsive Width: Instead of using a fixed width, we can use a responsive width (min-w or max-w) to allow the dropdown to adjust based on its content.
2. Overflow Handling: Ensure the content doesn't overflow by using overflow-hidden.
3. Adjust Padding and Margins: Fine-tune the padding and margins to ensure the content is well-positioned within the box.
> Fixed bug in Split screen for Support Us dropdown

- reportstary.css
help button position fixed
Closes: #issue_number
change the css of help button now it fixed to right side of screen .
> fixed position of help button in sos while scroll 

- blog.js
Closes: #issue_number
issue number: (#1562)
Made a minimal changes ensuring read button is inside a parent block.
> Fix the read button goes out it's parent block (#1562)

- light-dark-theme.js
Closes: #1702 
Hey @akshitagupta15june 
This PR adds functionality to persist the user's dark mode or light mode preference across page refreshes using localStorage. The changes ensure that the chosen theme state (either dark or light) remains consistent even after the user reloads the page.
https://github.com/akshitagupta15june/PetMe/assets/101971980/430e70e4-58ad-4c77-a1a2-5f8e819bf44a
> Fixed BUG "Persist Dark Mode/Light Mode Preference Across Page Refreshes"

- blog.html
- donate.html
- index.html
- navbar.css
- news.html
- reportstary.html
- volunteer.html
Closes: #1798
Added cursor-pointer and text-decoration underline on hover  in "Support-Us" bottom and fix some minor problems. 
Before👇
After👇
> Added cursor-pointer in "Support-Us" bottom #1798

- .vscode/settings.json
- index.html
- light-dark-theme.js
- output.css
- style.css
Closes: #1723 
[SSOC'24] contributor
Problem explanation:  In light mode, the "Contact Us" page has white font color on a light grey background. This makes the text difficult to read and not visually appealing. The font color needs to be changed to ensure better visibility and improve user experience.
Proposed Solution:
Change the font color to a darker shade.
- Added a class name "contact-form-text" to the contact us form in the index.html file to ensure consistency and easy targeting.
- Implemented a new JavaScript element in light-dark-theme.js specifically for managing the color toggling of the contact form text. This was done to address the issue of inconsistent text color in light mode.
- The corresponding CSS styles for the contact form text color were added in the output.css file …
> fetched and merged to resolve conflicts

- blog.html
- donate1.html
- light-dark-theme.js
- navbar.css
- volunteer.html
Closes: #1427
added dark mode for support and donate pages, also fixed the darkmode toggle button
> fix support and donate

- index.html
#1846  solved
#1846 
Closes: #1846  solved.
@akshitagupta15june 
dear admin please have look at this PR.
Contact Section color was too dark due to that the contact us was not visible it was merged with the background.
Here I fix all these issues by reducing the opacity from both the section as from contact and the body.
So if you like this change then please merge it and give the gssoc'24 level.
After change -
> #Contact Section background color improved. Now it looks good
